sudo: false
language: node_js
node_js:
  - '0.8'
  - '0.10'
  - '0.12'
  - '4'
  - '6'
before_install:
  - 'travis_retry npm install -g npm@2.14.5'
  - 'travis_retry npm install'
script:
  - 'npm test'
notifications:
  webhooks:
    urls:
      - 'https://www.travisbuddy.com/'
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: never
